### PR TITLE
Added option for tag to render_tree helper

### PR DESCRIPTION
**Pull request by m3nd3s**
I think is a good idea allow the users (developers) decide which tag
should be used when render_tree is calling, so I implemented it by
passing tag option in options hash.

### CODE REVIEW

**Comment by m3nd3s** [comment]
Continuing :)

Now I made a simple change in specific part of code (helper) and detailed what this option represents.

**Comment by m3nd3s** [comment]
Hi @skyeagle, did you generate a new version from that merge? I asked because the version on RubyGems still on 1.7.1 (without that tag option).

**Comment by skyeagle** [comment]
@m3nd3s I assume that it should be released with a little valuable feature than that. ;-) You could also point bundler to github master at any time.

**Comment by m3nd3s** [comment]
`;)` ok, no problem

**Pull request merged**
