### PR TITLE
Depths for nested items are not updated when parent items moves.

### PR DESCRIPTION
**Pull request by gzigzigzeo**
nested_set did not update cached depths for nested items: only for an item which was moved.

Here is the failing test:

  def test_depth_after_move
    categories(:child_2).move_to_root

```
assert_equal 0, categories(:child_2).reload.depth    
assert_equal 1, categories(:child_2_1).reload.depth

categories(:child_2).move_to_child_of(categories(:top_level_2))

assert_equal 1, categories(:child_2).reload.depth    
assert_equal 2, categories(:child_2_1).reload.depth
```

  end

And there is a solution in my pull request.

Also, I have added :depth_column option. It may simplify migration from other tree plugins and useful when depth is used for something else.

### CODE REVIEW

**Comment by skyeagle** [comment]
Could you cleanup trailing whitespaces and it will be great if these changes go in only one commit, please.

**Comment by gzigzigzeo** [comment]
Okay. Sorry for my inaccuracy. Could you tell me how to merge my four commits in one? I am not so familar to git.

**Comment by skyeagle** [comment]
You could read this http://feeding.cloud.geek.nz/2010/08/combining-multiple-commits-into-one.html

**Comment by gzigzigzeo** [comment]
Done

**Comment by skyeagle** [comment]
I've just merged and released 1.6.2 version. Thanks.

**Pull request closed without merging**
